apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
spec:
  selector:
    matchLabels:
      app: daemonapp
  template:
    metadata:
      app: daemonapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080